### ISSUE TITLE
How to navigate to another screen when switch is moved

### ISSUE THREAD

**Issue by vaqif14** [victorkvarghese/rn-slider-switch#3]
I want to add function onChange i tried but it can`t work please help to add function after moving slider

**Comment by victorkvarghese** [comment]
Use **onStatusChanged**
`  <MultiSwitch
          currentStatus="In Progress"
          disableScroll={value => {
            console.log("scrollEnabled", value);
            // this.scrollView.setNativeProps({
            //     scrollEnabled: value
            // });
          }}
          isParentScrollEnabled={false}
          onStatusChanged={text => {
            console.log("Change Status ", text);
            //add code to navigate here
          }}
          disableSwitch={false}
        />`
